### ISSUE TITLE
3d prints do not maintain anvil name after placing

### ISSUE THREAD

**Issue by Allymonies** [SwitchCraftCC/sc-peripherals#10]
If you name a 3d print (with or without a label) and place it down, and then break it, the custom name will not be retained. This differs from normal tile entity renaming behavior (in vanilla you can rename containers like chests and the name is preserved when breaking them).

![javaw_2023-01-23_21-46-22-17790](https://user-images.githubusercontent.com/7727003/214220902-80a6c514-abab-492e-9007-12a1eed5ddb0.png)
![javaw_2023-01-23_21-46-28-17791](https://user-images.githubusercontent.com/7727003/214220900-e579048c-f6c8-4478-83bc-a92f1d42a22c.png)

**Comment by hugeblank** [comment]
This *may* be intentional, given that prints are meant to behave more like blocks than they are tile entities.
