### ISSUE TITLE
The Ink Cartridge Suggestion

### ISSUE THREAD

**Issue by stealthy-coder** [SwitchCraftCC/sc-peripherals#15]
It's tooltip is "May be refilled useing dyes to use for 3D prints" however its now also used for the Wide Format Printer, which is not a 3D printer but a 2D Printer,
I propose the tooltip is changed to, "May be refilled useing dyes to use for all kinds of prints." or something similar.

**Comment by hugeblank** [comment]
https://github.com/SwitchCraftCC/sc-peripherals/blob/252d0fa97f450e622852105f32af3395c4190bc3/src/main/resources/assets/sc-peripherals/lang/en_us.json#L19 PRs welcome

**Comment by Lemmmy** [comment]
"for all kinds of prints" is too vague. The tooltips serve as their own documentation, so should be short but fully descriptive of what the item is useful for/can be used with. It also helps with keyword stuffing for REI searches.
