### ISSUE TITLE
Suggestion: Color paper printer

### ISSUE THREAD

**Issue by EmmaKnijn** [SwitchCraftCC/sc-peripherals#17]
You could implement a color printer that'll just print like a vanilla CC printer would, but would take ink cartridges and have options to change the text color (maybe with a setColor argument or just as an argument in the write function, depending on what the other printers use)

**Comment by Lemmmy** [comment]
I don't think this is suitable for the mod. I think the automation challenge of juggling different inks for printing in a vanilla CC printer is more interesting than having an equivalent in sc-peripherals that reimplements all the same code and takes away everything interesting about it.
