### ISSUE TITLE
[Feature Request] (Implementation will be provided via PR if accepted) Wearable 3D prints

### ISSUE THREAD

**Issue by AutumnalModding** [SwitchCraftCC/sc-peripherals#19]
I would love to be able to wear 3D prints in trinket slots (and potentially even a sort of "cosmetic armour" slot!).

If such a feature is permitted to be included in the mod, I'll start working on it and submit a PR for review whenever the maintainer(s?) of this repo feel like it (as I'm aware one of them is on vacation, and any potential other maintainers are probably busy with more important features).

(This issue is because I'd rather not work on a PR only for it to be denied.)

**Comment by Lemmmy** [comment]
Currently our plan is to have a supporter-exclusive hat slot that allows wearing the print _on top_ of the head rather than inside it, to complement the `/hat` command (and make this slot accept any item without the use of the command directly)

**Comment by AutumnalModding** [comment]
Ah, okay. No plans for any other slots, or non-supporter slots, then? (e.g. a back slot, or a "gauntlet" type slot [because the glove slot is already used])

**Comment by Lemmmy** [comment]
Not at the moment, but thank you for offering to PR! :) I'll leave this open for a while in case there are any further updates.

**Comment by AutumnalModding** [comment]
No problem :)

**Comment by scmcgowen** [comment]
I have a legitimate idea for an implementation of this: 3d prints can be crafted with a piece of armor to make the model replace the model of the armor.

**Comment by Lemmmy** [comment]
While it remains to be seen if this will make it into the base mod, this has now been implemented on SwitchCraft via [Supporter Customization](https://docs.sc3.io/faq/supporter.html#supporter-customization).
