### ISSUE TITLE
Posters and 3d prints lore does not show up as lore in CC detail lookups.

### ISSUE THREAD

**Issue by Wojbie** [SwitchCraftCC/sc-peripherals#22]
When inspecting details of items with lore in CC you can see that lore listed:
![obraz](https://user-images.githubusercontent.com/5893536/225995354-d8fd3362-199b-4e6b-9491-4869b0f8b73c.png)
![obraz](https://user-images.githubusercontent.com/5893536/225995393-7685961c-c301-404e-98e4-42e624d60fa0.png)

But with 3d prints and posters it does not seem to register:
![obraz](https://user-images.githubusercontent.com/5893536/225995501-222dc8e9-6225-4d09-b264-359adbf550f9.png)
![obraz](https://user-images.githubusercontent.com/5893536/225995554-4243230e-82dc-4da3-ae2b-34bac1c0883c.png)
![obraz](https://user-images.githubusercontent.com/5893536/225995689-cb733300-222b-48f1-a312-53a70500e917.png)
![obraz](https://user-images.githubusercontent.com/5893536/225995614-bae200fe-358e-4bb5-8801-855bab3873e8.png)

While not really critical it would be nice if this lore was consistent with MC lore?

**Comment by Lemmmy** [comment]
The two options I see here are implementing this in the Plethora API*, or transitioning to using the vanilla Lore tag. But that uses raw JSON, so it would be nontrivial to move our validation over to it. Will probably go the direction of Plethora API (result will still have Lore component probably)

*correction: implement this as an integration on Plethora's side
