### ISSUE TITLE
[Feature Request] Automatic renaming device

### ISSUE THREAD

**Issue by scmcgowen** [SwitchCraftCC/sc-peripherals#27]
This block would allow a computer to automatically rename items by putting items into its slot, running `peripheral.rename(name:string)` on it and then pulling the item from the block's inventory
 suggested crafting recipe: 
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/34895975/9bdd0467-4b53-4c42-8c88-98ed3414e124)

**Comment by scmcgowen** [comment]
initial comment edited to fix some formatting issues

**Comment by Lemmmy** [comment]
Thanks for the feature request. I can't think of any way to make this work within the paradigm of CC without introducing a whole new block. It's not trivial, or expected, for other peripheral mods to interact with CC's item transfer functions. And adding a whole new block for this just seems overkill.

The most CC-native approach that comes to mind is allowing turtles to use anvils in the same way as crafting tables, making use of a number of their internal slots, but you still have to consider how XP would be spent, and I don't think fuel is an appropriate equivalent.

With those points in mind; unless something really good comes along, I don't think I'm going to implement this.
