### ISSUE TITLE
[Feature Request] Add jamming to wide format printers and bad prints to 3d printers

### ISSUE THREAD

**Issue by dimaguy** [SwitchCraftCC/sc-peripherals#30]
In order to slow down the growth of the master file of posters, I propose that wide format printers find themselves jammed every now and then, requiring a player to manually go and fix them (like opening the GUI and clicking a button to solve the issue, a turtle could probably also do so if allowed in config file by going up to the printer and using a kinetic augment to clear the jam)
Wide format printers could have tiers, the more expensive they get, the less likely they are to jam, which would make it so services are more likely to use expensive printers(and having less of them at hand).

For 3d printers, the same strategy could be applied, but instead they could provide bad 3d prints, which would be missing parts from the model file or not being place-able at all

**Comment by Lemmmy** [comment]
```
sc@hiroi ~> du -sh /sc/server/world/data/posters
39M     /sc/server/world/data/posters
sc@hiroi ~> find /sc/server/world/data/posters -type f | wc -l
6137
```

I don't think the poster count is a concern. 70% of it is a giant Astolfo print which I still haven't seen placed anywhere

**Comment by dimaguy** [comment]
> ```
> sc@hiroi ~> du -sh /sc/server/world/data/posters
> 39M     /sc/server/world/data/posters
> sc@hiroi ~> find /sc/server/world/data/posters -type f | wc -l
> 6137
> ```
> 
> I don't think the poster count is a concern. 70% of it is a giant Astolfo print which I still haven't seen placed anywhere

It's on it's way to being placed, the canvas is awaiting for materials if I had to guess
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/7207103/dd21a1ed-79f0-498e-8601-73b543ed1782)

**Comment by dimaguy** [comment]
Also, it would provide for a more realistic experience on printers and make it more of a challenge to use them

**Comment by znepb** [comment]
This adds an unnecessary amount of complication to something that's already pretty difficult to achieve in mass. I don't like it.

**Comment by LDexter** [comment]
I value this highly, as the services that pour good money into gargantuan printing arrays will provide more value to the community. When your basic Mom and Pa setup at home can't seem to get past a 5-print failure streak, massive factories can shrug off that cost to time without breaking a sweat. Then people will invest not only towards commissions but also the act of printing on mass to offset this probability of failure. The investment makes krist flow and K's changing hands is what makes this cube go 'round!

**Comment by dimaguy** [comment]
> This adds an unnecessary amount of complication to something that's already pretty difficult to achieve in mass. I don't like it.

As per LDexter comment, it might balance in your favor if you have a good service, you can now actually build a moat for your business and have people get a reason to come to you instead of printing at home with 17kst nether star (aka. Easy to get) printers

**Comment by Lemmmy** [comment]
Sorry, this isn't a kitchen sink modpack, and we're not aiming for a 'realistic' experience.
