### ISSUE TITLE
3d prints do not affect light level of blocks

### ISSUE THREAD

**Issue by WindClan** [SwitchCraftCC/sc-peripherals#34]
Even if the 3d print stretches either the entire x and z dimensions or entire z/x and y it does not decrease light level leaving a weird fullbright like effect in structures made fully of these prints

**Comment by hugeblank** [comment]
If I'm reading this correctly you're saying that prints act as transparent blocks, even if they are full opaque textures?

If so, I'm not sure there's a way to easily fix this, as a print can partially or fully consist of translucent/transparent textures. It would be non-trivial to determine which faces do not allow light through.
