### ISSUE TITLE
[Feature Request] Model display transformations

### ISSUE THREAD

**Issue by penguinencounter** [SwitchCraftCC/sc-peripherals#35]
I would like to be able to adjust the view of 3D models in the GUI, item frames, in the hand, dropped on the ground, and in the head slot, a la the Blockbench Display tab. Ideally this would extend the .3dj spec, and be optional (use the default block transformations if none are provided.)

This should have no effect on the size of the displayed model when placed in-world.

This is possible by implementing `BakedModel#getTransformation` (which currently returns `ModelHelper.MODEL_TRANSFORM_BLOCK`.)

**Comment by Lemmmy** [comment]
Something similar to this is a planned feature for the Supporter system, but won't happen in the base mod. See #19

**Comment by penguinencounter** [comment]
Sorry, but I'm having a hard time understanding how this is related to #19. #19 is about actually *putting* prints on your head, this was about changing how the model is displayed - not on just the head, but also in the GUI etc.

Also, if this (or something similar) is planned for Supporter, I'm not sure how that could be implemented without checking and re-baking the model every time the model exits/enters a player inventory?

**Comment by Lemmmy** [comment]
Just for heads.
