### ISSUE TITLE
Rename Wide Format Printer to Poster Printer

### ISSUE THREAD

**Issue by khankul** [SwitchCraftCC/sc-peripherals#37]
for clarity's sake. It's named `sc-peripherals:poster_printer` anyway.
Shouldn't take much time, but do let me know if you'd like me to do the job.

**Comment by Kan18** [comment]
what about 2D printer? to contrast with 3D printer

**Comment by khankul** [comment]
I chose Poster Printer because of the ID, and I think 2D Printer is more likely to be confused for a regular ComputerCraft Printer.

**Comment by Lemmmy** [comment]
you've basically figured out why they're what they're called

**Comment by khankul** [comment]
I don't get it. = .=

**Comment by fucksophie** [comment]
+1, To chime in, the name of "Wide Format Printer" is almost always misleading because nowhere is it called an "Wide Format Printer" and it's called a poster printer in 99.99% of places. This renaming is very very much needed..

**Comment by emmachase** [comment]
Then we should rename it to wide format printer everywhere. Poster printer was shorthand because I felt like wide_format_printer was verbose.

**Comment by khankul** [comment]
Exactly - "Wide Format Printer" is unnecessarily verbose. And everyone will still call it a poster printer, just like Lemmmy themselves. Interestingly enough, they always referred to the item as "poster printer", I can't find any evidence in the chat suggesting otherwise.
![poster printer](https://github.com/SwitchCraftCC/sc-peripherals/assets/93801865/aaf2a98b-309e-47cc-911f-b045eeb54dad)
And a little bit of statistics:
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/93801865/7cbe08e3-49c5-418f-b7f6-163776052722)
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/93801865/1acc9def-aba4-4b1b-9eb4-6a7f6569141c)
So in my eyes, it is worth it to rename the item properly.

**Comment by emmachase** [comment]
For the record 77/106 is not very convincing.
