### ISSUE TITLE
[Feature Request] 3D print masking.

### ISSUE THREAD

**Issue by Darkodaaa** [SwitchCraftCC/sc-peripherals#38]
A new printer with another slot or a new slot for the printer.

This new slot could have a block in it and if you 3d print something that block gets used and the 3d print inherits most of the functionality of that block.

If a new printer and its recipe could have a nether star because that could make it a bit more expensive to mask with 3d prints.
If a new printer I'd be down to make its model.
If a new slot for the current printer then it could use I stack of a type of block to mask it to balance it more.

I know it's probably very unlikely that this is going to get added, but I asked some people and they liked the idea too.
I read through all of the issues open and closed with the keyword 3dprints and I didn't find anything related to this.

I hope for the best.

**Comment by Efealtan0909** [comment]
Sounds like a very cool idea!

Imagine if we could make special 3d prints that would mask cables and would be on the same block

**Comment by Lemmmy** [comment]
Are you asking for cable facades, or are you asking for mimics? Both are incredibly complex, but completely different feature requests. I don't think sc-peripherals is likely to implement anything like this.
