### ISSUE TITLE
Computers cannot access 3D printer slots

### ISSUE THREAD

**Issue by Lemmmy** [SwitchCraftCC/sc-peripherals#4]
The printer is not exposed as a generic inventory

**Comment by Lemmmy** [comment]
If my understanding is correct then this is not going to be trivial to fix:
- `InventoryMethods` is a GenericPeripheral, `PrinterPeripheral` is an IPeripheral
- A peripheral can not be both a GenericPeripheral and an IPeripheral (if I remember correctly? I didn't double check while writing this)
- Being a GenericPeripheral is necessary to receive the inventory methods
- Being an IPeripheral is necessary for `attach`/`detach` events, which allow us to track computers to send `3d_printer_state` events to
- GenericPeripherals do not (currently?) have a way to receive `attach`/`detach` events, or a list of computers that are attached to the peripheral

There are a few different approaches to this now:
- See if we can get CC to have attach/detach for GenericPeripherals somehow
- Go with GenericPeripheral and work around needing attach/detach by instead storing computer(s) who call the peripheral methods (or at least commit()) and only sending them the events
- Stick with IPeripheral and implement the inventory methods manually (similar to Plethora's InventoryMethodsWrapper)

**Comment by Wojbie** [comment]
But if i understand right you can still use `IPeripheral` peripherals as targets for inventory methods right (it works with turtles)? So one could call `chest.pushItems(Printername,1)` ?

**Comment by Lemmmy** [comment]
I believe so, but not because it's an IPeripheral, but rather because it's an Inventory (`Container` in mojmap)

https://github.com/cc-tweaked/CC-Tweaked/blob/2e5cd29e12db67c925c4ce5bd114c62d1bbae438/projects/fabric/src/main/java/dan200/computercraft/shared/peripheral/generic/methods/InventoryMethods.java#L139

**Comment by Wojbie** [comment]
So.. would making printer a container solve/alleviate this issue? Is that even feasible without some bodge code?

**Comment by Lemmmy** [comment]
It is a container

![image](https://user-images.githubusercontent.com/858456/216784221-a59b649e-b87d-4f4d-9973-f0931c914633.png)


I guess there's two issues at play here then
