### ISSUE TITLE
 Iron Ingots With NBT Data Cannot Be Used in the 3D Printer Recipe

### ISSUE THREAD

**Issue by Bioscreeper** [SwitchCraftCC/sc-peripherals#40]
Iron ingots with NBT data can't be used to craft a 3D printer.
Note that this may work with the other items in the recipe.

Steps to reproduce:
1. Add NBT data to some iron, e.g by renaming it.
2. Attempt to craft a 3D Printer

Expected Behaviour:
The 3D printer crafting recipe accepts any items matching the item type, but ignores any data associated with the item.
Then you are able to craft the item.

**Comment by Lemmmy** [comment]
![image](https://github.com/SwitchCraftCC/sc-peripherals/assets/858456/a173d400-710f-46d9-a326-04ea7fc1906c)
Named iron ingot works for me - were you using a computer with NBT data? That's not supported (it would destroy the computer/its data)

**Comment by Lemmmy** [comment]
User confirmed they were using a computer with NBT.
