### ISSUE TITLE
Changing print state resets print states of the prints directly around it

### ISSUE THREAD

**Issue by creeloper27** [SwitchCraftCC/sc-peripherals#45]
Rightclicking a print to change its state causes the prints directly around it to reset their state.

I wanted to have a small wall/canvas where you can input an image by toggling the print states but this bug makes it impossible to do so easily.

Example:
`test.3dj`
```
{
    "label": "test",
    "isButton": false,
    "collideWhenOn": true,
    "collideWhenOff": true,
    "lightLevel": 0,
    "redstoneLevel": 0,
    "shapesOff": [
        { "bounds": [0,0,0,16,16,16], "texture": "sc-peripherals:block/white", "tint": "000000"}
    ],
    "shapesOn": [
        { "bounds": [0,0,0,16,16,16], "texture": "sc-peripherals:block/white", "tint": "00FF00"}
    ]
}
```

https://github.com/SwitchCraftCC/sc-peripherals/assets/20074177/e7eea5b2-8ca2-46c5-b79e-d9672e8cc344

**Comment by Wojbie** [comment]
Duplicate #21
