### ISSUE TITLE
3d print seat position is offset upwards from designated position. 

### ISSUE THREAD

**Issue by Wojbie** [SwitchCraftCC/sc-peripherals#47]
As you can see in provided 0.1 , 0.5 and 0.9 screenshots player sitting positions seems to be offset upwards when sitting on 3d print. 

0.1 is just under middle of block
![obraz](https://github.com/SwitchCraftCC/sc-peripherals/assets/5893536/45fc8bb9-d1d6-4554-835e-af0a9bdbd746)
0.5 seems to be at 3/4ths
![obraz](https://github.com/SwitchCraftCC/sc-peripherals/assets/5893536/1eee22be-95fe-4461-be33-eaf4236bfaa1)
0.9 is above in next block
![obraz](https://github.com/SwitchCraftCC/sc-peripherals/assets/5893536/0e50a09f-d6d5-4efa-a52e-35f945e6ba79)

This is not client sided issue as other players also see offset position. This only appears to be a thing on vertical axis. Horizontal axis seems to work correctly.

**Comment by Lemmmy** [comment]
Fixed by https://github.com/SwitchCraftCC/sc-goodies/commit/3ec766478d34a98371fa0d41632dc6d42a0e3c21
